// Was auto-generated by `bal openapi`; hand-edited to add the /api/v1 base
// path, wire up config.bal's listener port, and implement the handlers.
// Endpoints not needed for the step-3 vertical slice return a placeholder
// "not_implemented" error and get filled in during step 4.
import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (listenPort);

function notImplementedError() returns Error => {
    'error: {code: "not_implemented", message: "this endpoint is built in plan.md step 4"}
};

service /api/v1 on ep0 {

    resource function delete posts/[int id]() returns http:NoContent|ErrorUnauthorized|ErrorForbidden|ErrorNotFound {
        return <ErrorNotFound>{body: notImplementedError()};
    }

    resource function get posts(boolean? published, int page = 1, int 'limit = 20) returns PostListResponse|ErrorBadRequest {
        return <ErrorBadRequest>{body: notImplementedError()};
    }

    # Fan-out join point (plan.md criterion #7): fetches the post's author and
    # comments concurrently via named `worker`s, then fetches each comment's
    # author concurrently too — the Ballerina-workers side of the
    # goroutines-vs-workers comparison.
    resource function get posts/[int id]() returns PostDetail|ErrorNotFound {
        PostRow|error postResult = getPostById(id);
        if postResult is error {
            return <ErrorNotFound>{body: {'error: {code: "not_found", message: "post not found"}}};
        }
        // Narrowing doesn't cross worker boundaries, so pull the fields the
        // workers need into plain locals before spawning them.
        PostRow post = postResult;
        int authorId = post.author_id;
        int postId = post.id;

        worker AuthorWorker returns UserRow|error {
            return getUserById(authorId);
        }
        worker CommentsWorker returns CommentRow[]|error {
            return listCommentsByPost(postId);
        }

        UserRow|error author = wait AuthorWorker;
        CommentRow[]|error comments = wait CommentsWorker;

        if author is error {
            log:printError("failed to load post author", author);
            return <ErrorNotFound>{body: {'error: {code: "internal_error", message: "could not load post detail"}}};
        }
        if comments is error {
            log:printError("failed to load comments", comments);
            return <ErrorNotFound>{body: {'error: {code: "internal_error", message: "could not load post detail"}}};
        }

        CommentWithAuthor[]|error commentsWithAuthors = fetchCommentAuthors(comments);
        if commentsWithAuthors is error {
            log:printError("failed to load comment authors", commentsWithAuthors);
            return <ErrorNotFound>{body: {'error: {code: "internal_error", message: "could not load post detail"}}};
        }

        return {
            id: post.id,
            author_id: post.author_id,
            title: post.title,
            body: post.body,
            published: post.published != 0,
            created_at: post.created_at,
            author: toApiUser(author),
            comments: commentsWithAuthors
        };
    }

    resource function get posts/[int id]/comments(int page = 1, int 'limit = 20) returns CommentListResponse|ErrorNotFound {
        return <ErrorNotFound>{body: notImplementedError()};
    }

    resource function post auth/login(@http:Payload LoginRequest payload) returns AuthResponseOk|ErrorBadRequest|ErrorUnauthorized {
        UserRow|error user = getUserByEmail(payload.email);
        if user is error || !checkPassword(user.password_hash, payload.password) {
            return <ErrorUnauthorized>{body: {'error: {code: "invalid_credentials", message: "email or password is incorrect"}}};
        }

        string|error token = issueToken(user.id);
        if token is error {
            log:printError("failed to issue token", token);
            return <ErrorUnauthorized>{body: {'error: {code: "internal_error", message: "could not issue token"}}};
        }

        return <AuthResponseOk>{body: {token, user: toApiUser(user)}};
    }

    resource function post auth/register(@http:Payload RegisterRequest payload) returns AuthResponse|ErrorBadRequest|ErrorConflict {
        string hash = hashPassword(payload.password);
        UserRow|error user = createUser(payload.username, payload.email, hash);
        if user is error {
            return <ErrorConflict>{body: {'error: {code: "user_exists", message: "username or email already registered"}}};
        }

        string|error token = issueToken(user.id);
        if token is error {
            log:printError("failed to issue token", token);
            return <ErrorConflict>{body: {'error: {code: "internal_error", message: "could not issue token"}}};
        }

        return {token, user: toApiUser(user)};
    }

    resource function post posts(@http:Payload CreatePostRequest payload) returns Post|ErrorBadRequest|ErrorUnauthorized {
        return <ErrorUnauthorized>{body: notImplementedError()};
    }

    resource function post posts/[int id]/comments(@http:Payload CreateCommentRequest payload) returns Comment|ErrorBadRequest|ErrorUnauthorized|ErrorNotFound {
        return <ErrorNotFound>{body: notImplementedError()};
    }

    resource function put posts/[int id](@http:Payload UpdatePostRequest payload) returns Post|ErrorBadRequest|ErrorUnauthorized|ErrorForbidden|ErrorNotFound {
        return <ErrorNotFound>{body: notImplementedError()};
    }
}

function toApiUser(UserRow u) returns User => {
    id: u.id,
    username: u.username,
    email: u.email,
    created_at: u.created_at
};

// Each comment author is fetched concurrently via `start`/`wait` futures —
// mirrors go/internal/handlers' errgroup fan-out at the same join point.
function fetchCommentAuthors(CommentRow[] comments) returns CommentWithAuthor[]|error {
    future<UserRow|error>[] futures = [];
    foreach CommentRow c in comments {
        future<UserRow|error> f = start getUserById(c.author_id);
        futures.push(f);
    }

    CommentWithAuthor[] result = [];
    foreach int i in 0 ..< comments.length() {
        UserRow author = check wait futures[i];
        CommentRow c = comments[i];
        result.push({
            id: c.id,
            post_id: c.post_id,
            author_id: c.author_id,
            body: c.body,
            created_at: c.created_at,
            author: toApiUser(author)
        });
    }
    return result;
}
