// Was auto-generated by `bal openapi`; hand-edited to add the /api/v1 base
// path, wire up config.bal's listener port, and implement the handlers.
import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (listenPort);

function errBody(string code, string message) returns Error => {
    'error: {code, message}
};

function toApiUser(UserRow u) returns User => {
    id: u.id,
    username: u.username,
    email: u.email,
    created_at: u.created_at
};

function toApiPost(PostRow p) returns Post => {
    id: p.id,
    author_id: p.author_id,
    title: p.title,
    body: p.body,
    published: p.published != 0,
    created_at: p.created_at
};

// Each comment author is fetched concurrently via `start`/`wait` futures —
// mirrors go/internal/handlers' errgroup fan-out at the same join point.
function attachAuthors(CommentRow[] comments) returns CommentWithAuthor[]|error {
    future<UserRow|error>[] futures = [];
    foreach CommentRow c in comments {
        future<UserRow|error> f = start getUserById(c.author_id);
        futures.push(f);
    }

    CommentWithAuthor[] result = [];
    foreach int i in 0 ..< comments.length() {
        UserRow author = check wait futures[i];
        CommentRow c = comments[i];
        result.push({
            id: c.id,
            post_id: c.post_id,
            author_id: c.author_id,
            body: c.body,
            created_at: c.created_at,
            author: toApiUser(author)
        });
    }
    return result;
}

service /api/v1 on ep0 {

    resource function post auth/register(@http:Payload RegisterRequest payload) returns AuthResponse|ErrorBadRequest|ErrorConflict {
        if payload.username.length() < 3 || payload.password.length() < 8 || payload.email.trim() == "" {
            return <ErrorBadRequest>{body: errBody("validation_failed", "username (>=3 chars), password (>=8 chars) and email are required")};
        }

        string hash = hashPassword(payload.password);
        UserRow|error user = createUser(payload.username, payload.email, hash);
        if user is error {
            return <ErrorConflict>{body: errBody("user_exists", "username or email already registered")};
        }

        string|error token = issueToken(user.id);
        if token is error {
            log:printError("failed to issue token", token);
            return <ErrorConflict>{body: errBody("internal_error", "could not issue token")};
        }

        return {token, user: toApiUser(user)};
    }

    resource function post auth/login(@http:Payload LoginRequest payload) returns AuthResponseOk|ErrorBadRequest|ErrorUnauthorized {
        UserRow|error user = getUserByEmail(payload.email);
        if user is error || !checkPassword(user.password_hash, payload.password) {
            return <ErrorUnauthorized>{body: errBody("invalid_credentials", "email or password is incorrect")};
        }

        string|error token = issueToken(user.id);
        if token is error {
            log:printError("failed to issue token", token);
            return <ErrorUnauthorized>{body: errBody("internal_error", "could not issue token")};
        }

        return <AuthResponseOk>{body: {token, user: toApiUser(user)}};
    }

    resource function get posts(boolean? published, int page = 1, int 'limit = 20) returns PostListResponse|ErrorBadRequest {
        if page < 1 || 'limit < 1 || 'limit > 100 {
            return <ErrorBadRequest>{body: errBody("validation_failed", "page must be >=1, limit must be 1-100")};
        }

        PostPage|error result = listPosts(published, 'limit, (page - 1) * 'limit);
        if result is error {
            log:printError("failed to list posts", result);
            return <ErrorBadRequest>{body: errBody("internal_error", "could not list posts")};
        }

        Post[] posts = from PostRow p in result.posts select toApiPost(p);
        return {posts, page, 'limit, total: result.total};
    }

    resource function post posts(http:Request req, @http:Payload CreatePostRequest payload) returns Post|ErrorBadRequest|ErrorUnauthorized {
        int|error uid = extractUserId(req);
        if uid is error {
            return <ErrorUnauthorized>{body: errBody("unauthorized", "missing or invalid bearer token")};
        }
        if payload.title.trim() == "" || payload.body.trim() == "" {
            return <ErrorBadRequest>{body: errBody("validation_failed", "title and body are required")};
        }
        if !isClean(payload.title + " " + payload.body) {
            return <ErrorBadRequest>{body: errBody("validation_failed", "content contains profanity")};
        }

        PostRow|error post = createPost(uid, payload.title, payload.body, payload.published);
        if post is error {
            log:printError("failed to create post", post);
            return <ErrorBadRequest>{body: errBody("internal_error", "could not create post")};
        }
        return toApiPost(post);
    }

    resource function get posts/[int id]() returns PostDetail|ErrorNotFound {
        PostRow|error postResult = getPostById(id);
        if postResult is error {
            return <ErrorNotFound>{body: errBody("not_found", "post not found")};
        }
        // Narrowing doesn't cross worker boundaries, so pull the fields the
        // workers need into plain locals before spawning them.
        PostRow post = postResult;
        int authorId = post.author_id;
        int postId = post.id;

        worker AuthorWorker returns UserRow|error {
            return getUserById(authorId);
        }
        worker CommentsWorker returns CommentRow[]|error {
            return listCommentsByPost(postId);
        }

        UserRow|error author = wait AuthorWorker;
        CommentRow[]|error comments = wait CommentsWorker;

        if author is error {
            log:printError("failed to load post author", author);
            return <ErrorNotFound>{body: errBody("internal_error", "could not load post detail")};
        }
        if comments is error {
            log:printError("failed to load comments", comments);
            return <ErrorNotFound>{body: errBody("internal_error", "could not load post detail")};
        }

        CommentWithAuthor[]|error commentsWithAuthors = attachAuthors(comments);
        if commentsWithAuthors is error {
            log:printError("failed to load comment authors", commentsWithAuthors);
            return <ErrorNotFound>{body: errBody("internal_error", "could not load post detail")};
        }

        return {
            id: post.id,
            author_id: post.author_id,
            title: post.title,
            body: post.body,
            published: post.published != 0,
            created_at: post.created_at,
            author: toApiUser(author),
            comments: commentsWithAuthors
        };
    }

    resource function put posts/[int id](http:Request req, @http:Payload UpdatePostRequest payload) returns Post|ErrorBadRequest|ErrorUnauthorized|ErrorForbidden|ErrorNotFound {
        int|error uid = extractUserId(req);
        if uid is error {
            return <ErrorUnauthorized>{body: errBody("unauthorized", "missing or invalid bearer token")};
        }

        PostRow|error existing = getPostById(id);
        if existing is error {
            return <ErrorNotFound>{body: errBody("not_found", "post not found")};
        }
        if existing.author_id != uid {
            return <ErrorForbidden>{body: errBody("forbidden", "only the author can modify this post")};
        }

        string? title = payload?.title;
        string? body = payload?.body;
        if title is string && title.trim() == "" {
            return <ErrorBadRequest>{body: errBody("validation_failed", "title cannot be empty")};
        }
        if body is string && body.trim() == "" {
            return <ErrorBadRequest>{body: errBody("validation_failed", "body cannot be empty")};
        }
        string checkText = (title ?: existing.title) + " " + (body ?: existing.body);
        if !isClean(checkText) {
            return <ErrorBadRequest>{body: errBody("validation_failed", "content contains profanity")};
        }

        PostRow|error updated = updatePost(id, title, body, payload?.published);
        if updated is error {
            log:printError("failed to update post", updated);
            return <ErrorBadRequest>{body: errBody("internal_error", "could not update post")};
        }
        return toApiPost(updated);
    }

    resource function delete posts/[int id](http:Request req) returns http:NoContent|ErrorUnauthorized|ErrorForbidden|ErrorNotFound {
        int|error uid = extractUserId(req);
        if uid is error {
            return <ErrorUnauthorized>{body: errBody("unauthorized", "missing or invalid bearer token")};
        }

        PostRow|error existing = getPostById(id);
        if existing is error {
            return <ErrorNotFound>{body: errBody("not_found", "post not found")};
        }
        if existing.author_id != uid {
            return <ErrorForbidden>{body: errBody("forbidden", "only the author can delete this post")};
        }

        error? result = deletePost(id);
        if result is error {
            log:printError("failed to delete post", result);
            return <ErrorNotFound>{body: errBody("internal_error", "could not delete post")};
        }
        return http:NO_CONTENT;
    }

    resource function get posts/[int id]/comments(int page = 1, int 'limit = 20) returns CommentListResponse|ErrorNotFound {
        PostRow|error post = getPostById(id);
        if post is error {
            return <ErrorNotFound>{body: errBody("not_found", "post not found")};
        }
        if page < 1 || 'limit < 1 || 'limit > 100 {
            return <ErrorNotFound>{body: errBody("validation_failed", "page must be >=1, limit must be 1-100")};
        }

        record {|CommentRow[] comments; int total;|}|error result = listCommentsPage(id, 'limit, (page - 1) * 'limit);
        if result is error {
            log:printError("failed to list comments", result);
            return <ErrorNotFound>{body: errBody("internal_error", "could not list comments")};
        }

        CommentWithAuthor[]|error withAuthors = attachAuthors(result.comments);
        if withAuthors is error {
            log:printError("failed to load comment authors", withAuthors);
            return <ErrorNotFound>{body: errBody("internal_error", "could not load comment authors")};
        }
        return {comments: withAuthors, page, 'limit, total: result.total};
    }

    resource function post posts/[int id]/comments(http:Request req, @http:Payload CreateCommentRequest payload) returns Comment|ErrorBadRequest|ErrorUnauthorized|ErrorNotFound {
        int|error uid = extractUserId(req);
        if uid is error {
            return <ErrorUnauthorized>{body: errBody("unauthorized", "missing or invalid bearer token")};
        }

        PostRow|error post = getPostById(id);
        if post is error {
            return <ErrorNotFound>{body: errBody("not_found", "post not found")};
        }
        if payload.body.trim() == "" {
            return <ErrorBadRequest>{body: errBody("validation_failed", "body is required")};
        }
        if !isClean(payload.body) {
            return <ErrorBadRequest>{body: errBody("validation_failed", "content contains profanity")};
        }

        CommentRow|error comment = createComment(id, uid, payload.body);
        if comment is error {
            log:printError("failed to create comment", comment);
            return <ErrorBadRequest>{body: errBody("internal_error", "could not create comment")};
        }
        return {
            id: comment.id,
            post_id: comment.post_id,
            author_id: comment.author_id,
            body: comment.body,
            created_at: comment.created_at
        };
    }
}
