// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

// @constraint:String annotations were removed here (they existed on
// RegisterRequest/CreatePostRequest/UpdatePostRequest/CreateCommentRequest):
// constraint validation runs before handler code and returns Ballerina's own
// error shape, not our {error:{code,message}} envelope — it broke plan.md
// criterion #5 (consistent error envelope). Validated in-handler instead,
// same as go/internal/handlers, so both stacks validate identically.
public type RegisterRequest record {
    string username;
    string email;
    string password;
};

public type Comment record {
    int id;
    int post_id;
    int author_id;
    string body;
    string created_at;
};

public type User record {
    int id;
    string username;
    string email;
    string created_at;
};

public type CreatePostRequest record {
    string title;
    string body;
    boolean published = false;
};

public type Post record {
    int id;
    int author_id;
    string title;
    string body;
    boolean published;
    string created_at;
};

public type ErrorConflict record {|
    *http:Conflict;
    Error body;
|};

public type Error record {
    Error_error 'error;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type LoginRequest record {
    string email;
    string password;
};

public type AuthResponseOk record {|
    *http:Ok;
    AuthResponse body;
|};

public type PostListResponse record {
    Post[] posts;
    int page;
    int 'limit;
    int total;
};

public type Error_error record {
    string code;
    string message;
    string details?;
};

public type AuthResponse record {
    string token;
    User user;
};

public type UpdatePostRequest record {
    string title?;
    string body?;
    boolean published?;
};

public type CommentWithAuthor record {
    *Comment;
    User author;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type CreateCommentRequest record {
    string body;
};

public type PostDetail record {
    *Post;
    User author;
    CommentWithAuthor[] comments;
};

public type ErrorForbidden record {|
    *http:Forbidden;
    Error body;
|};

public type CommentListResponse record {
    CommentWithAuthor[] comments;
    int page;
    int 'limit;
    int total;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
