// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/constraint;
import ballerina/http;

public type RegisterRequest record {
    @constraint:String {maxLength: 32, minLength: 3}
    string username;
    string email;
    @constraint:String {minLength: 8}
    string password;
};

public type Comment record {
    int id;
    int post_id;
    int author_id;
    string body;
    string created_at;
};

public type User record {
    int id;
    string username;
    string email;
    string created_at;
};

public type CreatePostRequest record {
    @constraint:String {maxLength: 200, minLength: 1}
    string title;
    @constraint:String {minLength: 1}
    string body;
    boolean published = false;
};

public type Post record {
    int id;
    int author_id;
    string title;
    string body;
    boolean published;
    string created_at;
};

public type ErrorConflict record {|
    *http:Conflict;
    Error body;
|};

public type Error record {
    Error_error 'error;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type LoginRequest record {
    string email;
    string password;
};

public type AuthResponseOk record {|
    *http:Ok;
    AuthResponse body;
|};

public type PostListResponse record {
    Post[] posts;
    int page;
    int 'limit;
    int total;
};

public type Error_error record {
    string code;
    string message;
    string details?;
};

public type AuthResponse record {
    string token;
    User user;
};

public type UpdatePostRequest record {
    @constraint:String {maxLength: 200, minLength: 1}
    string title?;
    @constraint:String {minLength: 1}
    string body?;
    boolean published?;
};

public type CommentWithAuthor record {
    *Comment;
    User author;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type CreateCommentRequest record {
    @constraint:String {minLength: 1}
    string body;
};

public type PostDetail record {
    *Post;
    User author;
    CommentWithAuthor[] comments;
};

public type ErrorForbidden record {|
    *http:Forbidden;
    Error body;
|};

public type CommentListResponse record {
    CommentWithAuthor[] comments;
    int page;
    int 'limit;
    int total;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
